version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: 'npm version check'
          command: npm --version
      - run:
          name: 'Node.js version check'          
          command: node --version
      - checkout
      - restore_cache:
          keys:
            - v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: 'Run build'
          command: npm run build
      - run:
          name: 'Deploy to Hosting'
          command: ./node_modules/.bin/firebase deploy --project "$FIREBASE_PROJECT_ID" --token="$FIREBASE_TOKEN"
  lint:
    docker:
      - image: node:14
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v2-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run lint
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
